// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.4
// source: cosf/cosf.proto

package cosf

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_cosf_cosf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AllocateQPSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Qps           int64                  `protobuf:"varint,2,opt,name=qps,proto3" json:"qps,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	BucketId      string                 `protobuf:"bytes,4,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`       // 可选，如果为空，则根据当前bucket查询可以授权的
	BusinessId    string                 `protobuf:"bytes,5,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"` // 可选，如果为空，则根据当前bucket查询可以授权的
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateQPSRequest) Reset() {
	*x = AllocateQPSRequest{}
	mi := &file_cosf_cosf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateQPSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateQPSRequest) ProtoMessage() {}

func (x *AllocateQPSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateQPSRequest.ProtoReflect.Descriptor instead.
func (*AllocateQPSRequest) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateQPSRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AllocateQPSRequest) GetQps() int64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *AllocateQPSRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *AllocateQPSRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *AllocateQPSRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type AllocateQPSResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Qps           int64                  `protobuf:"varint,2,opt,name=qps,proto3" json:"qps,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateQPSResponseData) Reset() {
	*x = AllocateQPSResponseData{}
	mi := &file_cosf_cosf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateQPSResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateQPSResponseData) ProtoMessage() {}

func (x *AllocateQPSResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateQPSResponseData.ProtoReflect.Descriptor instead.
func (*AllocateQPSResponseData) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateQPSResponseData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AllocateQPSResponseData) GetQps() int64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *AllocateQPSResponseData) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type AllocateQPSResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Base          *BaseResponse            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Data          *AllocateQPSResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateQPSResponse) Reset() {
	*x = AllocateQPSResponse{}
	mi := &file_cosf_cosf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateQPSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateQPSResponse) ProtoMessage() {}

func (x *AllocateQPSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateQPSResponse.ProtoReflect.Descriptor instead.
func (*AllocateQPSResponse) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{3}
}

func (x *AllocateQPSResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AllocateQPSResponse) GetData() *AllocateQPSResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_cosf_cosf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_cosf_cosf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CosKey        string                 `protobuf:"bytes,2,opt,name=cos_key,json=cosKey,proto3" json:"cos_key,omitempty"`
	BucketId      string                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_cosf_cosf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DownloadRequest) GetCosKey() string {
	if x != nil {
		return x.CosKey
	}
	return ""
}

func (x *DownloadRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_cosf_cosf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosf_cosf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_cosf_cosf_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DownloadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_cosf_cosf_proto protoreflect.FileDescriptor

const file_cosf_cosf_proto_rawDesc = "" +
	"\n" +
	"\x0fcosf/cosf.proto\x12\x04cosf\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x12AllocateQPSRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03qps\x18\x02 \x01(\x03R\x03qps\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\tR\bexpireAt\x12\x1b\n" +
	"\tbucket_id\x18\x04 \x01(\tR\bbucketId\x12\x1f\n" +
	"\vbusiness_id\x18\x05 \x01(\tR\n" +
	"businessId\"Z\n" +
	"\x17AllocateQPSResponseData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03qps\x18\x02 \x01(\x03R\x03qps\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\tR\bexpireAt\"p\n" +
	"\x13AllocateQPSResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.cosf.BaseResponseR\x04base\x121\n" +
	"\x04data\x18\x02 \x01(\v2\x1d.cosf.AllocateQPSResponseDataR\x04data\"\x14\n" +
	"\x12HealthCheckRequest\"=\n" +
	"\x13HealthCheckResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.cosf.BaseResponseR\x04base\"Y\n" +
	"\x0fDownloadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\acos_key\x18\x02 \x01(\tR\x06cosKey\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\"T\n" +
	"\x10DownloadResponse\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.cosf.BaseResponseR\x04base\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\xa4\x02\n" +
	"\vCosfService\x12]\n" +
	"\vHealthCheck\x12\x18.cosf.HealthCheckRequest\x1a\x19.cosf.HealthCheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/cosf/healthCheck\x12`\n" +
	"\vAllocateQPS\x12\x18.cosf.AllocateQPSRequest\x1a\x19.cosf.AllocateQPSResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/cosf/allocateQPS\x12T\n" +
	"\bDownload\x12\x15.cosf.DownloadRequest\x1a\x16.cosf.DownloadResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cosf/downloadB!Z\x1fgithub.com/bertguan96/cosf/cosfb\x06proto3"

var (
	file_cosf_cosf_proto_rawDescOnce sync.Once
	file_cosf_cosf_proto_rawDescData []byte
)

func file_cosf_cosf_proto_rawDescGZIP() []byte {
	file_cosf_cosf_proto_rawDescOnce.Do(func() {
		file_cosf_cosf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosf_cosf_proto_rawDesc), len(file_cosf_cosf_proto_rawDesc)))
	})
	return file_cosf_cosf_proto_rawDescData
}

var file_cosf_cosf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cosf_cosf_proto_goTypes = []any{
	(*BaseResponse)(nil),            // 0: cosf.BaseResponse
	(*AllocateQPSRequest)(nil),      // 1: cosf.AllocateQPSRequest
	(*AllocateQPSResponseData)(nil), // 2: cosf.AllocateQPSResponseData
	(*AllocateQPSResponse)(nil),     // 3: cosf.AllocateQPSResponse
	(*HealthCheckRequest)(nil),      // 4: cosf.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 5: cosf.HealthCheckResponse
	(*DownloadRequest)(nil),         // 6: cosf.DownloadRequest
	(*DownloadResponse)(nil),        // 7: cosf.DownloadResponse
}
var file_cosf_cosf_proto_depIdxs = []int32{
	0, // 0: cosf.AllocateQPSResponse.base:type_name -> cosf.BaseResponse
	2, // 1: cosf.AllocateQPSResponse.data:type_name -> cosf.AllocateQPSResponseData
	0, // 2: cosf.HealthCheckResponse.base:type_name -> cosf.BaseResponse
	0, // 3: cosf.DownloadResponse.base:type_name -> cosf.BaseResponse
	4, // 4: cosf.CosfService.HealthCheck:input_type -> cosf.HealthCheckRequest
	1, // 5: cosf.CosfService.AllocateQPS:input_type -> cosf.AllocateQPSRequest
	6, // 6: cosf.CosfService.Download:input_type -> cosf.DownloadRequest
	5, // 7: cosf.CosfService.HealthCheck:output_type -> cosf.HealthCheckResponse
	3, // 8: cosf.CosfService.AllocateQPS:output_type -> cosf.AllocateQPSResponse
	7, // 9: cosf.CosfService.Download:output_type -> cosf.DownloadResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cosf_cosf_proto_init() }
func file_cosf_cosf_proto_init() {
	if File_cosf_cosf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosf_cosf_proto_rawDesc), len(file_cosf_cosf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosf_cosf_proto_goTypes,
		DependencyIndexes: file_cosf_cosf_proto_depIdxs,
		MessageInfos:      file_cosf_cosf_proto_msgTypes,
	}.Build()
	File_cosf_cosf_proto = out.File
	file_cosf_cosf_proto_goTypes = nil
	file_cosf_cosf_proto_depIdxs = nil
}
